[tox]
envlist = py39, py310, py311, py312, py313, pre-commit, docs

[testenv]
extras = dev
commands =
    python -m coverage erase
    python -m coverage run -m pytest {posargs}
    python -m coverage report

[testenv:pre-commit]
skip_install = true
deps = pre-commit
commands = pre-commit run --all-files --show-diff-on-failure

[testenv:docs]
extras = docs
commands = mkdocs build --strict
